//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ex3servicewcf.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filiere", Namespace="http://schemas.datacontract.org/2004/07/ex3servicewcf")]
    [System.SerializableAttribute()]
    public partial class Filiere : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_filiereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_filiereField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_filiere {
            get {
                return this.Id_filiereField;
            }
            set {
                if ((this.Id_filiereField.Equals(value) != true)) {
                    this.Id_filiereField = value;
                    this.RaisePropertyChanged("Id_filiere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_filiere {
            get {
                return this.Nom_filiereField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_filiereField, value) != true)) {
                    this.Nom_filiereField = value;
                    this.RaisePropertyChanged("Nom_filiere");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFiliereService")]
    public interface IFiliereService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFiliereService/getAllFilieres", ReplyAction="http://tempuri.org/IFiliereService/getAllFilieresResponse")]
        ex3servicewcf.ServiceReference1.Filiere[] getAllFilieres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFiliereService/getAllFilieres", ReplyAction="http://tempuri.org/IFiliereService/getAllFilieresResponse")]
        System.Threading.Tasks.Task<ex3servicewcf.ServiceReference1.Filiere[]> getAllFilieresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFiliereServiceChannel : ex3servicewcf.ServiceReference1.IFiliereService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FiliereServiceClient : System.ServiceModel.ClientBase<ex3servicewcf.ServiceReference1.IFiliereService>, ex3servicewcf.ServiceReference1.IFiliereService {
        
        public FiliereServiceClient() {
        }
        
        public FiliereServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FiliereServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiliereServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiliereServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ex3servicewcf.ServiceReference1.Filiere[] getAllFilieres() {
            return base.Channel.getAllFilieres();
        }
        
        public System.Threading.Tasks.Task<ex3servicewcf.ServiceReference1.Filiere[]> getAllFilieresAsync() {
            return base.Channel.getAllFilieresAsync();
        }
    }
}
