//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ex4clientselfhosting.BonjourServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BonjourServiceReference.IBonjourService")]
    public interface IBonjourService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBonjourService/Bonjour", ReplyAction="http://tempuri.org/IBonjourService/BonjourResponse")]
        string Bonjour(string nom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBonjourService/Bonjour", ReplyAction="http://tempuri.org/IBonjourService/BonjourResponse")]
        System.Threading.Tasks.Task<string> BonjourAsync(string nom);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBonjourServiceChannel : ex4clientselfhosting.BonjourServiceReference.IBonjourService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BonjourServiceClient : System.ServiceModel.ClientBase<ex4clientselfhosting.BonjourServiceReference.IBonjourService>, ex4clientselfhosting.BonjourServiceReference.IBonjourService {
        
        public BonjourServiceClient() {
        }
        
        public BonjourServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BonjourServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BonjourServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BonjourServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Bonjour(string nom) {
            return base.Channel.Bonjour(nom);
        }
        
        public System.Threading.Tasks.Task<string> BonjourAsync(string nom) {
            return base.Channel.BonjourAsync(nom);
        }
    }
}
