<?xml version="1.0" encoding="utf-8"?><Database Name="gestion_etudiant" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-NDR7MD0;Initial Catalog=gestion_etudiant;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="gestion_etudiantConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Filiere" Member="Filiere">
    <Type Name="Filiere">
      <Column Name="Id_filiere" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nom_filiere" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>